### ISSUE TITLE
How to reproduce your segmentation result in paper?

### ISSUE THREAD

**Issue by Gregory1994** [OliverRensu/TinyMIM#3]
Hi, thanks for your great work!

I'm interested in your outstanding segentation result in TinyMIM-tiny, and try to reproduce it. But I only get 38.87 mIoU on ade20k dataset, considerably lower than 45.0 mIoU reported in your paper. 

I did my experiment on mmsegmentation and use TinyMIM-FT-Tstar.pth as pretrained model. 

So would you please tell me: 
1. how can I reproduce your segmentation result?
2. can you provide training setting or training log or segmentation checkpoints?

Best wishes!

**Comment by OliverRensu** [comment]
There is slight difference between TinyMIM and TinyMIM-T* including distillation tokens, number of heads, and an extra fully connected layer. The code will be released soon.
Please email me if you need the log and the code that I used but is not ready to be published in github for reference.

**Comment by Gregory1994** [comment]
> 

Thanks for your reply! i've emailed you and looking forward your code and log! I will close this issue.
