### ISSUE TITLE
The pos_embed's dimension of checkpoint `TinyMIM-FT-Tstar.pth`

### ISSUE THREAD

**Issue by RockeyCoss** [OliverRensu/TinyMIM#6]
Thanks for your wonderful work!
By the way, could you please tell me why the length of the `pos_embed` parameters in the checkpoint `TinyMIM-FT-Tstar.pth` is 198\(14\*14+2\) instead of 197\(14\*14+1\)? 
Thank you very much!

**Comment by OliverRensu** [comment]
We take knowledge distillation like DeiT in finetuning TinyMIM-Tstar, therefore, there is an extra distillation token.

**Comment by RockeyCoss** [comment]
Thank you very much! Is the first token the distillation token?

**Comment by OliverRensu** [comment]
No, the second token is the distillation token. You can refer https://github.com/OliverRensu/TinyMIM/blob/master/Segmentation/TinyMIMstar-T/backbone/mae.py

**Comment by RockeyCoss** [comment]
I see, thank you very much!
